# Generated by Django 4.1.7 on 2023-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam')], max_length=20, null=True),
        ),
    ]
