# Generated by Django 4.1.7 on 2023-04-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
